sudo: false
language: python
python:
  - "2.7"
branches:
  only:
    - master
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=$HOME/miniconda2/bin:$PATH
  - conda update --yes conda
  - pip install --upgrade pip
install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION numpy h5py
  - pip install --upgrade quantities nose
script:
  - nosetests
