sudo: false
language: python
python:
  - "2.7"
  - "3.6"
branches:
  only:
    - master
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=$HOME/miniconda2/bin:$PATH
  - conda create --yes -n myenv python=$TRAVIS_PYTHON_VERSION
  - source activate myenv
  - pip install --upgrade pip
install:
  - conda install --yes numpy h5py==2.3.1
  - pip install --upgrade quantities future requests
  - pip install pytest pytest-cov coveralls
  - pip install --upgrade docopt
script:
  - pytest --cov=h5py_wrapper
after_success:
  - coveralls

